name: 05-Simple Action
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
        - name: Simple JS Action
          id: hello
        #colocamos la ruta del action que queremos ejecutar y..
        #despues del @ ponemos la rama, tag o commit que queremos ejecutar, la version (tag)
          uses: actions/hello-world-javascript-action@v1.1 #https://github.com/actions/hello-world-javascript-action
          with:
            who-to-greet: 'Mona the Octocat'
        #Si el action tiene outputs, podemos acceder a ellos con steps.<id>.outputs.<nombre del output>
        - name: Log greeting time
          run: echo "The time was ${{ steps.hello.outputs.time }}"