name: 06-Checkout
on: [push]

#On PUSH
jobs: 
  checkout-action: #CHECKOUT con un ACTION (un solo paso)
    runs-on: ubuntu-latest
    steps:
        - name: List files before checkout
          run: ls -a

        - uses: actions/checkout@v4
  
        - name: List files after checkout
          run: ls -a
  
  checkout-and-display-files: #CHECKOUT donde nostros indicamos cada uno de los comandos
        runs-on: ubuntu-latest
        steps:
            - name: List files before checkout
              run: ls -a

            - name: Checkout repository
              run: |
                git init
                echo "PWD = $PWD"
                echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main

            - name: List files after checkout
              run: ls -a