name: 07-Repository Events
on: [push, pull_request, issues]

jobs: 
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: First step # prints the commit hash and the branch name
              run: |
                echo $GITHUB_SHA 
                echo $GITHUB_REF 
            - uses: actions/checkout@v3     # checkout the repository