#Events con Activity types 
#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

name: 08-Events Activity Types

on:
  push: #	Not applicable 
  pull_request: #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    types: [opened, assigned, reopened, synchronize]
  issues: #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
    types: [opened, closed, reopened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
    # Imprime el valor de las variables de entorno GITHUB_SHA(Hash) y GITHUB_REF (Referencia)
    - run: | #Contiene el hash del commit
          echo "Hash del commit: ${{ github.sha}}"  
          echo "Referencia del commit: ${{ github.ref }}"

    # Se encarga de clonar el repositorio en la máquina virtual
    - uses: actions/checkout@v3

      
#Podemos probar este caso al crear un pull request, asginar un pull request
