name: 15-Expressions & Context

on: [push, pull_request, issues, workflow_dispatch]

# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# @${{ github.actor }}: Menciona al usuario que ejecutó la acción   

# @${{}} significa que se está utilizando una expresión
# ${{}} significa que se está utilizando una variable de contexto

#Titulo dinamico para la ejecución
run-name: "Expresions & Context by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
    using-expressions-and-contexts:
        runs-on: ubuntu-latest

        # se ejecuta el job solo si el evento es un push
        # fijate que no hace falta los {} para la expresión if
        if: github.event_name == 'push'
        
        steps:
            # Ejemplo de como se pueden utilizar expresiones y literales
            - name: Expressiones
              run: |
                echo "1- Literal int: ${{ 1 }}"
                echo "2- Literal string: ${{ 'Hello, World!' }}"
                echo "3- Literal boolean: ${{ true }}"
                echo "6- Literal null: ${{ null }}"
                echo "7- Literal expression: ${{ 1>2 }}"
                echo "8- Literal expression: ${{ 'string' == 'String' }}"
                echo "9- Literal expression: ${{ true && false }}"
                echo "10- Literal expression: ${{ true || (false && true) }}"

             # Ejemplo de como se puede utilizar el contexto de GitHub Actions   
            - name: Contexts
              run: |
                echo "11- github.actor: ${{ github.actor }}"
                echo "12- github.run_id: ${{ github.run_id }}"
                echo "13- github.repository: ${{ github.repository }}"
                echo "14- github.event_name: ${{ github.event_name }}"
                echo "15- toJson(job): ${{ toJson(job) }}"
                echo "16- toJson(steps): ${{ toJson(steps) }}"
                echo "17- toJson(secrets): ${{ toJson(secrets) }}"
                echo "18- toJson(runner): ${{ toJson(runner) }}"
