name: 17-Environment Variables

on: [push]

# Variables de entorno globales a todos los jobs de este workflow
env:
  WF_ENV_VAR: "This is a custom environment variable"

jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest

        #En este caso se ejecuta el job solo si la rama es main
        # Es muy importante usar context variables en el if
        # Las variables de entorno NO se evaluan en el if
        if: github.ref == 'refs/heads/main'

        #NO HAGAS ESTO: Las variables de entorno NO se evaluan en el if 
        #if: $GITHUB_REF == 'refs/heads/main'

        # Variables de entorno especificas para este job
        env:
            JOB_ENV_VAR: "This is a custom environment variable for this job"


        steps:
            # Este paso imprime las variables de entorno
            # Runner Machine Environment Variables
            - name: Log ENV VAR
              run: echo $GITHUB_REF # Imprime la referencia de la rama
            
            # Este paso imprime el contexto de GitHub Actions
            # Enviado al runner por GitHub Actions
            # Se evalua antes de que se ejecute el job en el runner
            # Se envia al runner ya evaluado
            - name: Log Context
              run: echo '${{ github.ref }}' #Imprime la referencia de la rama


            - name: Set ENV VAR
            # Esto lo que hace es añadir una variable de entorno al runner
              run: echo "NEW_ENV_VAR=$(date)" >> $GITHUB_ENV    
            # Podemos sobre escribir las variables de entorno
            - name: Overwrite ENV VAR
              run: echo "JOB_ENV_VAR=$RANDOM" >> $GITHUB_ENV  

            - name: Multiple ENV VAR
              run: |
                DELIMITER=";" 
            
                echo "RANDOM_JOKE << $DELIMITER" >> $GITHUB_ENV
                echo "This is a random joke" >> $GITHUB_ENV
                curl -s https://api.chucknorris.io/jokes/random | jq -r '.value' >> $GITHUB_ENV
                echo "" >> $GITHUB_ENV
                
                echo "$DELIMITER" >> $GITHUB_ENV


            # Variables de entorno globales para este step del job  
            - name: Log Custom ENV VAR
              env:
                STEP_ENV_VAR: "This is a custom environment variable for this step"
                #Se pueden sobreescribir las variables de entorno globales
                WF_ENV_VAR: "Overwritten global environment variable"

              run: |
                # Imprime la variable de entorno global
                echo $WF_ENV_VAR 
                
                # Imprime la variable de entorno del job
                echo $JOB_ENV_VAR 

                # Imprime la variable de entorno del step
                echo $STEP_ENV_VAR 

                # Imprime la variable de entorno del step
                echo $NEW_ENV_VAR

                # Imprime la variable de entorno del step
                echo $RANDOM_JOKE

            
            