name: 17-Vars and Secrets

on: [push]

jobs:
    decrypt-file:
        runs-on: ${{ vars.JOBS_RUNNER }}
        steps:
            - uses: actions/checkout@v3
            - name: Decrypt file
              env:
                PASSPHRASE: ${{ secrets.PASSPHRASE }}
              run: |
                mkdir $HOME/secrets
                gpg --quiet --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output secrets.txt secrets.txt.gpg
                cat secrets.txt

    log-vars:
        # Usar una variable del repositorio
        runs-on: ${{ vars.JOBS_RUNNER }}

        # Definir un entorno
        environment: "production"

        # Variables de entorno
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}


        steps:
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true' 
              run: echo "I ran"


            - name: Log Vars
              run: |
                echo '${{ vars.JOBS_RUNNER }}'
                echo ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
                echo REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}     


