name: Checkout
on: [push]


jobs: 
  checkout-action:
    runs-on: ubuntu-latest
    steps:
        - name: List files before checkout
          run: ls -a

        - uses: actions/checkout@v4
  
        - name: List files after checkout
          run: ls -a
  
  checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before checkout
              run: ls -a
            - name: Checkout repository
              run: |
                git init
                echo "$PWD"
                echo "$GITHUB_REPOSITORY"
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout master
            - name: List files after checkout
              run: ls -a